spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_APP_JAR
          value: ${project.artifactId}-${project.versionId}.war
      resources:
        limits:
          memory: 250Mi